insert into Product (id, product_name, store_name, store_address) values (1, 'Castor canadensis', 'Thoughtbeat', '76 Arrowood Circle');
insert into Product (id, product_name, store_name, store_address) values (2, 'Bubo virginianus', 'Brainbox', '49069 Bayside Way');
insert into Product (id, product_name, store_name, store_address) values (3, 'Spermophilus lateralis', 'Geba', '95 Orin Circle');
insert into Product (id, product_name, store_name, store_address) values (4, 'Tachyglossus aculeatus', 'Roodel', '6790 Parkside Park');
insert into Product (id, product_name, store_name, store_address) values (5, 'Neotis denhami', 'Babbleopia', '14605 Dapin Lane');
insert into Product (id, product_name, store_name, store_address) values (6, 'Acrantophis madagascariensis', 'Riffwire', '06086 Fordem Park');
insert into Product (id, product_name, store_name, store_address) values (7, 'Sylvilagus floridanus', 'Thoughtsphere', '256 Dovetail Parkway');
insert into Product (id, product_name, store_name, store_address) values (8, 'Sylvicapra grimma', 'Photojam', '4274 Sutteridge Court');
insert into Product (id, product_name, store_name, store_address) values (9, 'Macropus parryi', 'Thoughtblab', '8 Sherman Park');
insert into Product (id, product_name, store_name, store_address) values (10, 'Tachyglossus aculeatus', 'Skipstorm', '73 Tennyson Point');
insert into Product (id, product_name, store_name, store_address) values (11, 'Geochelone elegans', 'Podcat', '9 Ryan Place');
insert into Product (id, product_name, store_name, store_address) values (12, 'Geococcyx californianus', 'Lazz', '64481 Hauk Lane');
insert into Product (id, product_name, store_name, store_address) values (13, 'Gerbillus sp.', 'Eamia', '1 Knutson Court');
insert into Product (id, product_name, store_name, store_address) values (14, 'Cercatetus concinnus', 'Teklist', '7 Bartelt Crossing');
insert into Product (id, product_name, store_name, store_address) values (15, 'Turtur chalcospilos', 'Wikibox', '9139 Sullivan Terrace');
insert into Product (id, product_name, store_name, store_address) values (16, 'Bradypus tridactylus', 'Linkbridge', '9186 Ridgeway Point');
insert into Product (id, product_name, store_name, store_address) values (17, 'Myiarchus tuberculifer', 'Linktype', '60 Eggendart Road');
insert into Product (id, product_name, store_name, store_address) values (18, 'Lutra canadensis', 'Skaboo', '0 Florence Circle');
insert into Product (id, product_name, store_name, store_address) values (19, 'Anthropoides paradisea', 'Skiba', '826 Montana Trail');
insert into Product (id, product_name, store_name, store_address) values (20, 'Centrocercus urophasianus', 'Oyondu', '6998 Mariners Cove Center');
insert into Product (id, product_name, store_name, store_address) values (21, 'Plectopterus gambensis', 'Pixoboo', '1675 Debra Road');
insert into Product (id, product_name, store_name, store_address) values (22, 'Phalaropus fulicarius', 'Twitterbridge', '850 Rusk Plaza');
insert into Product (id, product_name, store_name, store_address) values (23, 'Panthera tigris', 'Zoombox', '175 Mockingbird Park');
insert into Product (id, product_name, store_name, store_address) values (24, 'Cebus apella', 'Yozio', '36 Sloan Way');
insert into Product (id, product_name, store_name, store_address) values (25, 'Acrobates pygmaeus', 'Fanoodle', '56549 Norway Maple Point');
insert into Product (id, product_name, store_name, store_address) values (26, 'Amblyrhynchus cristatus', 'Topicstorm', '8 Monterey Pass');
insert into Product (id, product_name, store_name, store_address) values (27, 'Phoca vitulina', 'Youspan', '736 Northwestern Park');
insert into Product (id, product_name, store_name, store_address) values (28, 'Lamprotornis sp.', 'Topiczoom', '52983 Mcguire Road');
insert into Product (id, product_name, store_name, store_address) values (29, 'Platalea leucordia', 'Thoughtblab', '87492 Talisman Crossing');
insert into Product (id, product_name, store_name, store_address) values (30, 'Megaderma spasma', 'Tanoodle', '294 Judy Way');
insert into Product (id, product_name, store_name, store_address) values (31, 'Pelecans onocratalus', 'Zoomdog', '654 Forest Dale Drive');
insert into Product (id, product_name, store_name, store_address) values (32, 'Acinynox jubatus', 'Oyoloo', '8 Sloan Terrace');
insert into Product (id, product_name, store_name, store_address) values (33, 'Genetta genetta', 'Realpoint', '26 Vermont Center');
insert into Product (id, product_name, store_name, store_address) values (34, 'Tayassu tajacu', 'Dazzlesphere', '7339 Twin Pines Lane');
insert into Product (id, product_name, store_name, store_address) values (35, 'Bugeranus caruncalatus', 'Dabshots', '795 East Street');
insert into Product (id, product_name, store_name, store_address) values (36, 'Canis lupus baileyi', 'Bubblemix', '3 Dunning Drive');
insert into Product (id, product_name, store_name, store_address) values (37, 'Ardea golieth', 'Quinu', '6268 Vermont Drive');
insert into Product (id, product_name, store_name, store_address) values (38, 'Sylvilagus floridanus', 'Roombo', '57825 Oakridge Lane');
insert into Product (id, product_name, store_name, store_address) values (39, 'Passer domesticus', 'Browseblab', '59227 Kingsford Point');
insert into Product (id, product_name, store_name, store_address) values (40, 'Gyps bengalensis', 'Realmix', '8 Hagan Avenue');
insert into Product (id, product_name, store_name, store_address) values (41, 'Bubalornis niger', 'Voomm', '22885 Burning Wood Avenue');
insert into Product (id, product_name, store_name, store_address) values (42, 'Semnopithecus entellus', 'Avavee', '1313 Charing Cross Alley');
insert into Product (id, product_name, store_name, store_address) values (43, 'Antechinus flavipes', 'Voomm', '0 Hallows Crossing');
insert into Product (id, product_name, store_name, store_address) values (44, 'Chlamydosaurus kingii', 'Zava', '4 Fairfield Parkway');
insert into Product (id, product_name, store_name, store_address) values (45, 'Centrocercus urophasianus', 'Geba', '1 Delladonna Place');
insert into Product (id, product_name, store_name, store_address) values (46, 'Diomedea irrorata', 'Feedfish', '1 Park Meadow Terrace');
insert into Product (id, product_name, store_name, store_address) values (47, 'Canis aureus', 'Mydeo', '281 Carey Avenue');
insert into Product (id, product_name, store_name, store_address) values (48, 'Phoenicopterus ruber', 'Skimia', '94948 Magdeline Crossing');
insert into Product (id, product_name, store_name, store_address) values (49, 'Crocodylus niloticus', 'Eidel', '251 Haas Avenue');
insert into Product (id, product_name, store_name, store_address) values (50, 'Ateles paniscus', 'Eabox', '19 David Street');
insert into Product (id, product_name, store_name, store_address) values (51, 'Stenella coeruleoalba', 'JumpXS', '7 Clove Parkway');
insert into Product (id, product_name, store_name, store_address) values (52, 'Phoenicopterus ruber', 'JumpXS', '00 Towne Parkway');
insert into Product (id, product_name, store_name, store_address) values (53, 'Boa constrictor mexicana', 'Chatterbridge', '77936 Crowley Drive');
insert into Product (id, product_name, store_name, store_address) values (54, 'Dasyurus viverrinus', 'Latz', '05 Gina Park');
insert into Product (id, product_name, store_name, store_address) values (55, 'Cracticus nigroagularis', 'Jaxworks', '03 Dahle Lane');
insert into Product (id, product_name, store_name, store_address) values (56, 'Phoenicopterus chilensis', 'Kwilith', '9 Orin Plaza');
insert into Product (id, product_name, store_name, store_address) values (57, 'Anser caerulescens', 'Jamia', '2 Porter Way');
insert into Product (id, product_name, store_name, store_address) values (58, 'Kobus leche robertsi', 'Skyndu', '9008 Forest Run Avenue');
insert into Product (id, product_name, store_name, store_address) values (59, 'Phoca vitulina', 'Yadel', '5 Rutledge Place');
insert into Product (id, product_name, store_name, store_address) values (60, 'Gyps bengalensis', 'DabZ', '4883 Chive Crossing');
insert into Product (id, product_name, store_name, store_address) values (61, 'Nucifraga columbiana', 'Yakidoo', '8039 Veith Place');
insert into Product (id, product_name, store_name, store_address) values (62, 'Pandon haliaetus', 'Agimba', '69296 Norway Maple Parkway');
insert into Product (id, product_name, store_name, store_address) values (63, 'Hystrix cristata', 'Ntags', '513 Becker Avenue');
insert into Product (id, product_name, store_name, store_address) values (64, 'Aonyx cinerea', 'Agivu', '7 Golden Leaf Lane');
insert into Product (id, product_name, store_name, store_address) values (65, 'Haliaeetus leucoryphus', 'Meeveo', '4 Loeprich Hill');
insert into Product (id, product_name, store_name, store_address) values (66, 'Cebus albifrons', 'Skidoo', '7779 Fordem Terrace');
insert into Product (id, product_name, store_name, store_address) values (67, 'Alligator mississippiensis', 'Rhyloo', '1 Express Alley');
insert into Product (id, product_name, store_name, store_address) values (68, 'Cervus elaphus', 'Rooxo', '00 Clemons Circle');
insert into Product (id, product_name, store_name, store_address) values (69, 'Sciurus vulgaris', 'Voolia', '2 West Point');
insert into Product (id, product_name, store_name, store_address) values (70, 'Paraxerus cepapi', 'Gabspot', '01580 Troy Road');
insert into Product (id, product_name, store_name, store_address) values (71, 'Charadrius tricollaris', 'Mynte', '65863 Clarendon Court');
insert into Product (id, product_name, store_name, store_address) values (72, 'Rhea americana', 'Plambee', '76 Southridge Road');
insert into Product (id, product_name, store_name, store_address) values (73, 'Alcelaphus buselaphus cokii', 'Fivebridge', '2010 Kinsman Hill');
insert into Product (id, product_name, store_name, store_address) values (74, 'Phascogale calura', 'Centizu', '419 Lighthouse Bay Court');
insert into Product (id, product_name, store_name, store_address) values (75, 'Stercorarius longicausus', 'Jabberbean', '5 Melby Road');
insert into Product (id, product_name, store_name, store_address) values (76, 'Mazama gouazoubira', 'Fivespan', '6030 Algoma Street');
insert into Product (id, product_name, store_name, store_address) values (77, 'Ardea cinerea', 'Buzzster', '54 Northridge Point');
insert into Product (id, product_name, store_name, store_address) values (78, 'Madoqua kirkii', 'Voonte', '28 Dawn Place');
insert into Product (id, product_name, store_name, store_address) values (79, 'Spheniscus mendiculus', 'Zoozzy', '7 Merchant Road');
insert into Product (id, product_name, store_name, store_address) values (80, 'Lamprotornis superbus', 'Pixonyx', '5445 Hoard Street');
insert into Product (id, product_name, store_name, store_address) values (81, 'Porphyrio porphyrio', 'Ooba', '7151 Washington Crossing');
insert into Product (id, product_name, store_name, store_address) values (82, 'Climacteris melanura', 'Tazz', '29 Orin Terrace');
insert into Product (id, product_name, store_name, store_address) values (83, 'Butorides striatus', 'Leexo', '184 Village Junction');
insert into Product (id, product_name, store_name, store_address) values (84, 'Canis aureus', 'Flipopia', '7477 Lunder Way');
insert into Product (id, product_name, store_name, store_address) values (85, 'Naja haje', 'Oyoba', '865 Kropf Crossing');
insert into Product (id, product_name, store_name, store_address) values (86, 'Centrocercus urophasianus', 'Vimbo', '9137 Sunnyside Drive');
insert into Product (id, product_name, store_name, store_address) values (87, 'Panthera leo', 'Cogilith', '78 Thackeray Place');
insert into Product (id, product_name, store_name, store_address) values (88, 'Centrocercus urophasianus', 'Fivebridge', '7 Delaware Circle');
insert into Product (id, product_name, store_name, store_address) values (89, 'unavailable', 'Devpulse', '6 Superior Street');
insert into Product (id, product_name, store_name, store_address) values (90, 'Propithecus verreauxi', 'Skilith', '38 Warrior Crossing');
insert into Product (id, product_name, store_name, store_address) values (91, 'Uraeginthus granatina', 'Jaxbean', '9 Eagle Crest Junction');
insert into Product (id, product_name, store_name, store_address) values (92, 'Phoenicopterus ruber', 'Tambee', '70057 Gateway Avenue');
insert into Product (id, product_name, store_name, store_address) values (93, 'Upupa epops', 'Twitterbridge', '93122 Warner Way');
insert into Product (id, product_name, store_name, store_address) values (94, 'Anas bahamensis', 'Chatterpoint', '7881 Kipling Center');
insert into Product (id, product_name, store_name, store_address) values (95, 'Papilio canadensis', 'Twimbo', '33955 Kipling Point');
insert into Product (id, product_name, store_name, store_address) values (96, 'Dendrocygna viduata', 'Buzzdog', '38115 Brickson Park Place');
insert into Product (id, product_name, store_name, store_address) values (97, 'Semnopithecus entellus', 'Vipe', '41462 Spaight Pass');
insert into Product (id, product_name, store_name, store_address) values (98, 'Bassariscus astutus', 'Gigaclub', '83 Bluestem Junction');
insert into Product (id, product_name, store_name, store_address) values (99, 'Cereopsis novaehollandiae', 'Skalith', '77361 Eastwood Hill');
insert into Product (id, product_name, store_name, store_address) values (100, 'Ciconia ciconia', 'Livefish', '5291 Bluejay Court');
