CREATE TABLE Students(
    id INTEGER PRIMARY KEY,
	enrollNumber INTEGER NOT NULL,
    firstName VARCHAR(50) NOT NULL,
    surnames VARCHAR(100) NOT NULL,
    fullName VARCHAR(150) NOT NULL,
    semester INTEGER NOT NULL,
    birthdate DATE NOT NULL,
    email VARCHAR(150) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    phoneNumber VARCHAR(10) NOT NULL,
    address VARCHAR(150)
);

CREATE TABLE Users(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(500) NOT NULL,
    CONSTRAINT UC_USER_EMAIL UNIQUE (email)
);