insert into Store (id, store_name, store_address) values (1, 'Pixonyx', '92037 Claremont Hill');
insert into Store (id, store_name, store_address) values (2, 'Zooveo', '14 Bay Park');
insert into Store (id, store_name, store_address) values (3, 'Izio', '47159 Ilene Junction');
insert into Store (id, store_name, store_address) values (4, 'Vimbo', '0495 Killdeer Crossing');
insert into Store (id, store_name, store_address) values (5, 'Buzzshare', '2 Karstens Alley');
insert into Store (id, store_name, store_address) values (6, 'Bluejam', '537 Loftsgordon Parkway');
insert into Store (id, store_name, store_address) values (7, 'Trilia', '0579 Burrows Drive');
insert into Store (id, store_name, store_address) values (8, 'Quinu', '390 Commercial Center');
insert into Store (id, store_name, store_address) values (9, 'Ainyx', '3022 Roxbury Circle');
insert into Store (id, store_name, store_address) values (10, 'Photobug', '151 Corry Road');
insert into Store (id, store_name, store_address) values (11, 'Bubbletube', '2341 Ridgeway Junction');
insert into Store (id, store_name, store_address) values (12, 'Kare', '24 Buhler Lane');
insert into Store (id, store_name, store_address) values (13, 'Twimbo', '050 Division Way');
insert into Store (id, store_name, store_address) values (14, 'Dablist', '63 Nancy Park');
insert into Store (id, store_name, store_address) values (15, 'Gigashots', '660 Lake View Trail');
insert into Store (id, store_name, store_address) values (16, 'Skyba', '835 Fulton Court');
insert into Store (id, store_name, store_address) values (17, 'Skyba', '2414 Fisk Trail');
insert into Store (id, store_name, store_address) values (18, 'Wikizz', '08055 Clarendon Avenue');
insert into Store (id, store_name, store_address) values (19, 'Zazio', '0 Tennessee Crossing');
insert into Store (id, store_name, store_address) values (20, 'Brainlounge', '12 Redwing Circle');
insert into Store (id, store_name, store_address) values (21, 'Skyndu', '9613 Sherman Alley');
insert into Store (id, store_name, store_address) values (22, 'Dabfeed', '303 Kings Street');
insert into Store (id, store_name, store_address) values (23, 'Oyoloo', '19 Butternut Court');
insert into Store (id, store_name, store_address) values (24, 'Cogidoo', '0534 Anderson Way');
insert into Store (id, store_name, store_address) values (25, 'Pixonyx', '763 Lindbergh Terrace');
insert into Store (id, store_name, store_address) values (26, 'Lazz', '88409 Toban Plaza');
insert into Store (id, store_name, store_address) values (27, 'Trupe', '16 Moulton Drive');
insert into Store (id, store_name, store_address) values (28, 'Myworks', '976 Browning Place');
insert into Store (id, store_name, store_address) values (29, 'Dazzlesphere', '66489 Eagle Crest Hill');
insert into Store (id, store_name, store_address) values (30, 'Skiptube', '6 American Junction');
insert into Store (id, store_name, store_address) values (31, 'Oozz', '993 Forest Dale Parkway');
insert into Store (id, store_name, store_address) values (32, 'Twitterlist', '34525 Mendota Alley');
insert into Store (id, store_name, store_address) values (33, 'Twiyo', '5095 Bartelt Road');
insert into Store (id, store_name, store_address) values (34, 'Zoombeat', '89 Basil Avenue');
insert into Store (id, store_name, store_address) values (35, 'Gigaclub', '2 Pine View Lane');
insert into Store (id, store_name, store_address) values (36, 'Roodel', '50352 Homewood Point');
insert into Store (id, store_name, store_address) values (37, 'Riffpedia', '5408 Darwin Park');
insert into Store (id, store_name, store_address) values (38, 'Feedfire', '7860 Blue Bill Park Junction');
insert into Store (id, store_name, store_address) values (39, 'Meemm', '3 Atwood Trail');
insert into Store (id, store_name, store_address) values (40, 'Latz', '345 Beilfuss Way');
insert into Store (id, store_name, store_address) values (41, 'Yadel', '739 Rigney Street');
insert into Store (id, store_name, store_address) values (42, 'Kanoodle', '67 Park Meadow Center');
insert into Store (id, store_name, store_address) values (43, 'Shuffletag', '83 Clarendon Trail');
insert into Store (id, store_name, store_address) values (44, 'Youfeed', '30 Tomscot Hill');
insert into Store (id, store_name, store_address) values (45, 'Jabberstorm', '4627 Memorial Alley');
insert into Store (id, store_name, store_address) values (46, 'Cogidoo', '3475 Straubel Crossing');
insert into Store (id, store_name, store_address) values (47, 'Kaymbo', '7946 Dryden Hill');
insert into Store (id, store_name, store_address) values (48, 'Zooveo', '25290 Delladonna Lane');
insert into Store (id, store_name, store_address) values (49, 'Oodoo', '29 Corry Street');
insert into Store (id, store_name, store_address) values (50, 'Tazz', '519 Northport Drive');
insert into Store (id, store_name, store_address) values (51, 'Riffpedia', '38078 Fair Oaks Terrace');
insert into Store (id, store_name, store_address) values (52, 'Fivespan', '0 Pankratz Court');
insert into Store (id, store_name, store_address) values (53, 'Mynte', '66122 Badeau Lane');
insert into Store (id, store_name, store_address) values (54, 'Skyndu', '93230 Tennyson Hill');
insert into Store (id, store_name, store_address) values (55, 'Twiyo', '7107 8th Pass');
insert into Store (id, store_name, store_address) values (56, 'Lazz', '57 Meadow Ridge Park');
insert into Store (id, store_name, store_address) values (57, 'Tagcat', '2983 Vermont Way');
insert into Store (id, store_name, store_address) values (58, 'Fivebridge', '51 Dakota Plaza');
insert into Store (id, store_name, store_address) values (59, 'Tagchat', '6 Kipling Court');
insert into Store (id, store_name, store_address) values (60, 'Eamia', '58 Canary Lane');
insert into Store (id, store_name, store_address) values (61, 'Demizz', '57121 Oakridge Street');
insert into Store (id, store_name, store_address) values (62, 'Aimbu', '5249 Milwaukee Terrace');
insert into Store (id, store_name, store_address) values (63, 'Trupe', '645 Roxbury Crossing');
insert into Store (id, store_name, store_address) values (64, 'Bubbletube', '55014 Upham Center');
insert into Store (id, store_name, store_address) values (65, 'Zoomdog', '198 Valley Edge Alley');
insert into Store (id, store_name, store_address) values (66, 'Quimm', '71 Hoffman Terrace');
insert into Store (id, store_name, store_address) values (67, 'Snaptags', '79426 High Crossing Road');
insert into Store (id, store_name, store_address) values (68, 'Gigaclub', '932 Shasta Parkway');
insert into Store (id, store_name, store_address) values (69, 'Layo', '7 Walton Trail');
insert into Store (id, store_name, store_address) values (70, 'Blogspan', '4 Northwestern Crossing');
insert into Store (id, store_name, store_address) values (71, 'Izio', '550 Fieldstone Park');
insert into Store (id, store_name, store_address) values (72, 'Snaptags', '4 Columbus Hill');
insert into Store (id, store_name, store_address) values (73, 'Livefish', '04 Goodland Court');
insert into Store (id, store_name, store_address) values (74, 'Edgeblab', '25757 Manley Parkway');
insert into Store (id, store_name, store_address) values (75, 'Tagchat', '3143 Thierer Point');
insert into Store (id, store_name, store_address) values (76, 'Innotype', '80 Bultman Avenue');
insert into Store (id, store_name, store_address) values (77, 'Photolist', '763 Monica Crossing');
insert into Store (id, store_name, store_address) values (78, 'Oyope', '26575 Nobel Hill');
insert into Store (id, store_name, store_address) values (79, 'Thoughtworks', '85453 Goodland Park');
insert into Store (id, store_name, store_address) values (80, 'Yamia', '69263 Golf Course Terrace');
insert into Store (id, store_name, store_address) values (81, 'Jayo', '21459 Forest Alley');
insert into Store (id, store_name, store_address) values (82, 'Tekfly', '098 Manitowish Junction');
insert into Store (id, store_name, store_address) values (83, 'Brainbox', '9 Clyde Gallagher Circle');
insert into Store (id, store_name, store_address) values (84, 'Tagfeed', '6 Forest Dale Street');
insert into Store (id, store_name, store_address) values (85, 'Bubblebox', '4592 Oak Valley Point');
insert into Store (id, store_name, store_address) values (86, 'Buzzbean', '85986 Towne Park');
insert into Store (id, store_name, store_address) values (87, 'Skyvu', '4405 Linden Hill');
insert into Store (id, store_name, store_address) values (88, 'Dabfeed', '463 Red Cloud Center');
insert into Store (id, store_name, store_address) values (89, 'Zooveo', '8 Monterey Circle');
insert into Store (id, store_name, store_address) values (90, 'Youbridge', '40 Truax Plaza');
insert into Store (id, store_name, store_address) values (91, 'Zoonoodle', '712 Goodland Place');
insert into Store (id, store_name, store_address) values (92, 'Izio', '5 Mccormick Crossing');
insert into Store (id, store_name, store_address) values (93, 'Innotype', '822 Vidon Lane');
insert into Store (id, store_name, store_address) values (94, 'Aibox', '07 Blaine Junction');
insert into Store (id, store_name, store_address) values (95, 'Babbleset', '52 Namekagon Place');
insert into Store (id, store_name, store_address) values (96, 'Eazzy', '247 Cascade Alley');
insert into Store (id, store_name, store_address) values (97, 'Mita', '94815 Hayes Pass');
insert into Store (id, store_name, store_address) values (98, 'Mynte', '6816 Boyd Way');
insert into Store (id, store_name, store_address) values (99, 'Blogpad', '898 3rd Plaza');
insert into Store (id, store_name, store_address) values (100, 'Brainverse', '7789 Debs Point');
